name: "Build static"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get Repo Name
        run: |
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -f 2 -d '/')" >> $GITHUB_ENV

      - name: Check Repo Name
        run: |
          echo "Repo Name: $REPO_NAME"

      - name: Create .env file
        run: touch .env && echo "VITE_REPO_NAME=$REPO_NAME" >> .env

      - name: Install Dependencies & Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build

      - name: Change Base
        run: sed -i "s/assets/$REPO_NAME\/assets/g" ./dist/index.html

      - name: Create 404.html
        run: cp ./dist/index.html ./dist/404.html

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./dist"

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
